### PR TITLE
Fujinet Version 1.0: Added insert for plug to minimize possibility of…

### PR DESCRIPTION
**Pull request by jhusak**
… ping breaking when not evenly inserted.

### CODE REVIEW

**Comment by mozzwald** [comment]
There's no way to secure this plug in the case. The latest v1.5 design uses the same idea you have here with the slots for pins and will also fit the v1.0 hardware
https://github.com/FujiNetWIFI/fujinet-hardware/blob/master/FN32ROV-1.5-Q24/3D-Files/FujiNet-SIO-Plug_REVC_20201229.stl

**Comment by jhusak** [comment]
Hello.   I have secured my plug this way (tested), so it _is_ the way.  Maybe you think about other way.  Otherways, if you do not want to put it into repository, I&#39;ll put this on thingiverse, but this generate mess.  So please consider again adding this to repo. The manual how to use it can be put to some text file...   Montage instructions:  - put insert part onto pcb  - put pins (at least those zaxon uses) into holes till stop  - solder them.  - glue the original part onto it.  - end   Near is how it looks after mount :)   Dnia 3 maja 2021 19:05 mozzwald ***@***.***&gt; napisał(a):   There&#39;s no way to secure this plug in the case. The latest v1.5 design uses the same idea you have here with the slots for pins and will also fit the v1.0 hardware    github.com github.com  —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .

**Comment by mozzwald** [comment]
Maybe I'm confused about what this part is for. Can you post a picture of the real thing in use on a FujiNet?

I recommend you take a look at the part I linked in my previous post. It works with all FujiNet hardware versions. Insert pins into plug, insert into board and solder all the pins.

**Comment by jhusak** [comment]
Hello.   Of course I have seen next version of the part. It resolves problems with zaxon&#39;s pins breaking only partially. For some reason he uses 1.0 plugin for 1.0 devices...  My part fits inside plug of 1.0 (as zaxon uses) and prevents breaking pins when not evenly inserted with force.   In attachements you can see the problem and salvation. The insert guarantees that pin will not break in it&#39;s weakest part.  I think adding them to the repository is minor for you but major for users like me for project (it is the &#34;upgrade&#34; for older parts), it has nothing in common with newer parts.   BDW. Could you provide photo/link of the pins that you use?   Best Regards   Jakub Husak Dnia 4 maja 2021 02:48 mozzwald ***@***.***&gt; napisał(a):   Maybe I&#39;m confused about what this part is for. Can you post a picture of the real thing in use on a FujiNet?  I recommend you take a look at the part I linked in my previous post. It works with all FujiNet hardware versions. Insert pins into plug, insert into board and solder all the pins.  —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .

**Pull request closed without merging**
